#if !canImport(ObjectiveC)
import XCTest

extension PygmentsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PygmentsTests = [
        ("testExample", testExample),
    ]
}

extension XcodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcodeTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PygmentsTests.__allTests__PygmentsTests),
        testCase(XcodeTests.__allTests__XcodeTests),
    ]
}
#endif
